// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('e:/Sasha/work/indexoft/react-native/aTommy/node_modules/react');
var { Component } = React;
var ReactNative = require('e:/Sasha/work/indexoft/react-native/aTommy/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('e:/Sasha/work/indexoft/react-native/aTommy/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('aTommy', appParameters);
});